apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: minicurso
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: requena/minik8s-stress
    ports:
    - containerPort: 80
